{{- if .Values.service.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "wmaker-ng.fullname" . }}
  labels:
    {{- include "wmaker-ng.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app.kubernetes.io/name: {{ include "wmaker-ng.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
  ports:
    - name: mcp
      port: {{ .Values.service.mcpPort }}
      targetPort: mcp
    - name: novnc
      port: {{ .Values.service.novncPort }}
      targetPort: novnc
{{- end }}
